### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by brightly-salty** [Marwes/combine-language#14]
Is this repository still maintained, or is it unmaintained/deprecated? I saw the last commit was two-three years ago.

I'm wondering because I was considering using combine to lex/parse my new programming language. While I was researching combine vs nom, I saw combine-language, which would fulfill all my current needs if it is still maintained.

I might be interested in contributing to (or maybe even maintaining) this if that would be all right.

Thanks,
brightlySalty

**Comment by Marwes** [comment]
While I am not actively working on this I did forget to update this to combine 4.x. Just updated and released a 4.x compatible version now though!

**Comment by brightly-salty** [comment]
Okay, thanks!
