### ISSUE TITLE
How to parse float numbers without integer?

### ISSUE THREAD

**Issue by agatan** [Marwes/combine-language#8]
I want to parse just float numbers, but `combine_language` doesn't provide such functionality.

for example:

``` rust
let parser = env.float();
parser.parse("123.45"); // => Ok(123.45)
parser.parse("123"); // => currently, Ok(123). But I think it should not be matched.
```

Are there any functions for this purpose?
If not, How do you think to add it?

**Comment by Marwes** [comment]
Tested how parsec's float parser works and it failed on `123` so I think I will just do the same thing. Is it ok that it parses an exponent or do you need a parser which only accepts `123.45` and not `123.45e-13`?

**Comment by agatan** [comment]
Thank you for the quick reply.
In my use case, it is preferable that `float` parser accepts both of `123.45` and `123.45e-13`.
If possible, I want to contribute to this library and try to implement them.

And also, is it better for `float` parser to accept `123e3`?
I think it should be accepted as Rust's syntax.
